version: 0.2

phases:
  install:
    commands:
      - echo Installing dependency...
      - npm install
  pre_build:
    commands:
      - REACT_APP_ENVIRONMENT=$DEPLOY_ENV
  build:
    commands:
      - echo Building code ...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  base-directory: .next
  files:
    - '**/*'


